### ISSUE TITLE
Uncaught recursion in getWhereUsedTree

### ISSUE THREAD

**Issue by ByteDoc** [neptune-software-marketplace/neptunesoftware-dxp-abb-devinfo#1]
Function getWhereUsedTree does not check for recursion (the way that function getUsingTree already does).

@lloyd-neptune @jeugro are such github issues a good thing in your workflow?
Maybe even pull requests here as well?
Where would you want me to post such issues/input?

My thoughts:
support-ticket-system ... too tedious for small things, especially for smaller Marketplace artifacts that are not "DXP core functionailty
community post, feature request ... seems to unspecific, untargeted

**Comment by jeugro** [comment]
@ByteDoc this is definitely a good place, thanks a lot for contributing to this

I'm just wondering how you committed the changes to the script because I'm basically missing a new version of the main app json file. And because the app has no new version I think your changes are not taken into account when pulling the repo into a system where the package already is present.

**Comment by ByteDoc** [comment]
I first changed the app on a customer system, no integration to our github account. And for a quick test I just forked the repo and edited the relevant file directly, using the changes I made on the customer system.
If this way of communicating issues/requests is fine, then I will set up our dev system for better pull requests :)

Anything you can think of I should pay attention to specifically when forking, changing on our dev system and creating pull requests?

**Comment by jeugro** [comment]
The procedure seems to work fine, I just needed to revert back the Git URL for the package from your fork to the "master" repo.
Thanks again for the fixes, closing this now.
